apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
        - name: book-catalog
          image: s224403789/week08:1
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgresql://week08_949u_user:iVDPbpkJ1wZqVSu5jLcpWmefncHrU3Hc@dpg-crlqt0jv2p9s73e2vl1g-a.oregon-postgres.render.com/week08_949u"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
